const SQL_SELECT_ALL = 'SELECT * FROM TBL_DEVICE;'
const SQL_SELECT_DEVICE_ID = 'SELECT * FROM TBL_DEVICE_CAMERA WHERE DEVICE_ID="1";'
const SQL_SELECT_DEVICE_WITH_CAMERA = 'SELECT * FROM TBL_DEVICE_CAMERA WHERE DEVICE_ID IS NOT NULL;'
const SQL_SELECT_DEVICES_START_WITH_FRONT = 'SELECT * FROM TBL_DEVICE_CAMERA WHERE NAME LIKE "Front%";'
const SQL_UPDATE_DEVICE_RECORD = 'UPDATE TBL_DEVICE_CAMERA SET NAME="Front Door Camera" WHERE id=18;'

export {
    SQL_SELECT_ALL,
    SQL_SELECT_DEVICE_ID,
    SQL_SELECT_DEVICE_WITH_CAMERA,
    SQL_SELECT_DEVICES_START_WITH_FRONT,
    SQL_UPDATE_DEVICE_RECORD
}